# Generated by Django 4.2.13 on 2024-06-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='total_marks',
            new_name='marks',
        ),
    ]
