# Generated by Django 4.2.13 on 2024-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0002_alter_task_due_date_alter_task_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_volunteers_number_accepted',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
