# Generated by Django 4.2.13 on 2024-06-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccountApp', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('volunteer', 'Volunteer'), ('leader', 'Leader'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
